import 'package:transfor_admin_dashboard/services/localizations.dart';

enum AppStrings {
  appTitle,
  loginTitle,
  email,
  password,
  login,
  loginFailed,
  adminIsNotFound,
  passwordIsWrong,
  hi,
  account,
  logout,
  dashboard,
  users,
  serviceProvider,
  driver,
  currentOrders,
  completedOrders,
  cancelledOrders,
  payoutRequest,
  settings,
  providers,
  products,
  services,
  ongoingOrders,
  search,
  addUser,
  addProvider,
  addDriver,
  no,
  name,
  mobile,
  date,
  action,
  vehicleDetails,
  vehicleDocumemts,
  vehicleType,
  vehiclePhoto,
  vehicleCertificate,
  licenseFront,
  licenseBack,
  small,
  medium,
  large,
  transportMaterials,
  companyDetails,
  companyName,
  companyDescription,
  userDetails,
  providerDetails,
  driverDetails,
  bankDetails,
  ibanImage,
  corporateRegistration,
  ibanNumber,
  userIsNotFound,
  bankInfoIsNotFound,
  companyIsNotFound,
  vehicleIsNotFound,
  userAndCompanyAreNotFound,
  userAndVehicleAreNotFound,
  userAndBankInfoAreNotFound,
  companyAndBankInfoAreNotFound,
  userAndcompanyAndBankInfoAreNotFound,
  vehicleAndBankInfoAreNotFound,
  userAndVehicleAndBankInfoAreNotFound,
  orderNo,
  amount,
  type,
  status,
  requestId,
  platformCharge,
  tax,
  adminProfile,
  save,
  fetchError,
  payoutHistory,
  paid,
  pendingProviders,
  pendingDrivers,
  confirm,
}

extension TKeysExtention on AppStrings {
  String get _string => toString().split('.')[1];

  String translate(context) {
    return AppLocalizations.of(context).translate(_string);
  }
}
